### ISSUE TITLE
Postfix is adding vps.localdomain domain to some messages created by Drupal

### ISSUE THREAD

**Issue by alexanderzatko** [sk-vpohybe/nabezky.sk#5]
The mail.log is full of such entries. I tried to resolve this issue for couple of hours, but apparently without success. All "important" mail seems to be delivered correctly, but it would be nice to resolve this issue as well.

**Comment by petervojtek** [comment]
similar issue:

```
              The mail system
```

the.fastest@azet.sk: host smtp2.azet.sk[91.235.53.42] said: 554 5.7.1
   the.fastest@azet.sk: Recipient address rejected: Invalid HELO/EHLO;
   Cannot resolve 'vps.localdomain', no such domain (in reply to RCPT TO
   command)
Reporting-MTA: dns; vps.localdomain
X-Postfix-Queue-ID: 886443E20090
X-Postfix-Sender: rfc822; posli@nabezky.sk
Arrival-Date: Sun,  3 Mar 2013 16:21:07 +0100 (CET)

Final-Recipient: rfc822; the.fastest@azet.sk
Action: failed
Status: 5.7.1
Remote-MTA: dns; smtp2.azet.sk
Diagnostic-Code: smtp; 554 5.7.1 the.fastest@azet.sk: Recipient address
   rejected: Invalid HELO/EHLO; Cannot resolve 'vps.localdomain', no such
   domain

**Comment by alexanderzatko** [comment]
opravene, alebo nesposobuje problem.
